# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-PatternMatching
version:      1.02
version_from: lib/Sub/PatternMatching.pm
installdirs:  site
requires:
    Params::Validate:              0.69
    Test::More:                    0
    Test::Pod:                     1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
